# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from athenian.api.models.base_model_ import Model
from athenian.api import util


class DeveloperSet(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):
        """DeveloperSet - a model defined in OpenAPI

        """
        self.openapi_types = {}

        self.attribute_map = {}

    @classmethod
    def from_dict(cls, dikt: dict) -> "DeveloperSet":
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The DeveloperSet of this DeveloperSet.
        """
        return util.deserialize_model(dikt, cls)
