# coding: utf-8

from athenian.api import util
from athenian.api.models.base_model_ import Model


class Granularity(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    DAY = "day"
    WEEK = "week"
    MONTH = "month"

    def __init__(self):
        """Granularity - a model defined in OpenAPI"""
        self.openapi_types = {}

        self.attribute_map = {}

    @classmethod
    def from_dict(cls, dikt: dict) -> "Granularity":
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Granularity of this Granularity.
        """
        return util.deserialize_model(dikt, cls)
