version: 2
updates:
- package-ecosystem: pip
  directory: "/server"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: coverage
    versions:
    - ">= 5.3.a, < 5.4"
  - dependency-name: flogging
    versions:
    - ">= 0.0.13.a, < 0.0.14"
  - dependency-name: gcloud-aio-auth
    versions:
    - "> 3.4.4, < 3.5"
  - dependency-name: gcloud-aio-kms
    versions:
    - ">= 3.3.a, < 3.4"
  - dependency-name: numpy
    versions:
    - "> 1.19.1, < 1.20"
  - dependency-name: openapi-spec-validator
    versions:
    - ">= 0.3.0.a, < 0.3.1"
  - dependency-name: prometheus-client
    versions:
    - "> 0.8.0, < 1"
  - dependency-name: scipy
    versions:
    - "> 1.5.2, < 1.6"
  - dependency-name: sentry-sdk[pure_eval]
    versions:
    - "> 0.17.3, < 0.18"
  - dependency-name: scipy
    versions:
    - 1.6.1
    - 1.6.2
    - 1.6.3
  - dependency-name: sqlalchemy
    versions:
    - 1.4.11
    - 1.4.2
    - 1.4.3
    - 1.4.5
    - 1.4.7
    - 1.4.9
  - dependency-name: flake8
    versions:
    - 3.9.1
  - dependency-name: pandas
    versions:
    - 1.2.1
    - 1.2.2
    - 1.2.3
  - dependency-name: semgrep
    versions:
    - 0.44.0
  - dependency-name: faker
    versions:
    - 6.6.3
  - dependency-name: numpy
    versions:
    - 1.20.2
