- name: Native
  paths:
  - "**.pyx"
  - "**.pyd"
  - "**.h"
  teams:
  - api-admin
- name: Guts
  paths:
  - "server/athenian/api/internal/features/**"
  - "server/athenian/api/internal/miners/**"
  - "server/athenian/api/internal/prefixer.py"
  teams:
  - api-admin
- name: DB
  paths:
  - "server/athenian/api/models/metadata/**"
  - "server/athenian/api/models/precomputed/**"
  - "server/athenian/api/models/persistentdata/**"
  teams:
  - api-admin
- name: Engine
  paths:
  - "server/athenian/api/async_utils.py"
  - "server/athenian/api/auth.py"
  - "server/athenian/api/cache.py"
  - "server/athenian/api/defer.py"
  - "server/athenian/api/faster_pandas.py"
  - "server/athenian/api/int_to_str.py"
  - "server/athenian/api/serialization.py"
  - "server/athenian/api/tracing.py"
  - "server/athenian/api/typing_utils.py"
  - "Dockerfile"
  - "pyproject.toml"
  - "requirements.txt"
  - "setup.py"
  - ".github/**"
  teams:
  - api-admin
