"**.pyx":
- team: api-admin
"**.pyd":
- team: api-admin
"**.h":
- team: api-admin

"server/athenian/api/internal/features/**":
- team: api-admin
"server/athenian/api/internal/miners/**":
- team: api-admin
"server/athenian/api/internal/prefixer.py":
- team: api-admin

"server/athenian/api/models/metadata/**":
- team: api-admin
"server/athenian/api/models/precomputed/**":
- team: api-admin
"server/athenian/api/models/persistentdata/**":
- team: api-admin

"server/athenian/api/async_utils.py":
- team: api-admin
"server/athenian/api/auth.py":
- team: api-admin
"server/athenian/api/cache.py":
- team: api-admin
"server/athenian/api/defer.py":
- team: api-admin
"server/athenian/api/faster_pandas.py":
- team: api-admin
"server/athenian/api/int_to_str.py":
- team: api-admin
"server/athenian/api/serialization.py":
- team: api-admin
"server/athenian/api/tracing.py":
- team: api-admin
"server/athenian/api/typing_utils.py":
- team: api-admin
"Dockerfile":
- team: api-admin
"pyproject.toml":
- team: api-admin
"requirements.txt":
- team: api-admin
"setup.py":
- team: api-admin
".github/**":
- team: api-admin
