comment: false
ignore:
  - server/athenian/api/hacks/reproduce_bug.py
coverage:
  status:
    patch: off
    project:
      default:
        target: auto
        threshold: 0%
        informational: true
        paths:
          - "server/athenian/api"