comment: false
fixes:
  - "server/::"
ignore:
  - athenian/api/hacks/show_body.py
  - athenian/api/hacks/show_sql.py
  - athenian/api/hacks/webapp.py
coverage:
  status:
    patch: off
    project:
      default:
        target: auto
        threshold: 0%
        informational: true
        paths:
          - "server/athenian/api"