language: python
python: 3.7
sudo: true
dist: bionic
branches:
  only:
  - master

env:
  global:
    - GOOGLE_DOCKER_IMAGE=gcr.io/athenian-1/api
    - IMAGE_BRANCH_COMMIT=${GOOGLE_DOCKER_IMAGE}:${TRAVIS_BRANCH}-${TRAVIS_COMMIT:0:7}

cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/google-cloud-sdk/"
    - "$HOME/docker"

before_cache:
  - chown -R travis:travis $HOME/.cache/pip
  - docker save -o $HOME/docker/images.tar ${GOOGLE_DOCKER_IMAGE}:latest

matrix:
  fast_finish: true
  include:
    - name: Unit tests and style check
      install:
        - cd server
        - pip install -r requirements.txt
        - pip install -r lint-requirements.txt
        - pip install -r test-requirements.txt
        - pip install -e .
      script:
        - flake8
        - pytest
        - python3 -m athenian.api.models.state sqlite://
    - if: type = pull_request
      name: Docker build smoke test
      before_install:
        - docker load -i $HOME/docker/images.tar || true
        - docker image list
      install:
        - docker build --cache-from ${GOOGLE_DOCKER_IMAGE}:latest -t ${GOOGLE_DOCKER_IMAGE} .
      script:
        - docker run --rm ${GOOGLE_DOCKER_IMAGE} --help
    - stage: deploy
      if: branch = master AND type != pull_request
      script:
        - docker load -i $HOME/docker/images.tar || true
        - docker image list
        - docker build --cache-from ${GOOGLE_DOCKER_IMAGE} -t ${IMAGE_BRANCH_COMMIT} .
        - make gcloud-login
        - IMAGE=${IMAGE_BRANCH_COMMIT} make docker-push
        - IMAGE=${IMAGE_BRANCH_COMMIT} make pubsub-publish
        - docker tag ${IMAGE_BRANCH_COMMIT} ${GOOGLE_DOCKER_IMAGE}
        - IMAGE=${GOOGLE_DOCKER_IMAGE} make docker-push

notifications:
  email: false