language: python
python: 3.8
os: linux
dist: bionic
group: dev
branches:
  only:
  - master

env:
  global:
    - GOOGLE_DOCKER_IMAGE=gcr.io/athenian-1/api

cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/google-cloud-sdk/"
    - "$HOME/docker"

before_cache:
  - chown -R travis:travis $HOME/.cache/pip
  - docker save -o $HOME/docker/images.tar ${GOOGLE_DOCKER_IMAGE}:latest


matrix:
  fast_finish: true
  include:
    - if: branch = master AND type != pull_request AND commit_message =~ /^Bump version/
      name: Deploy
      install:
        - curl -sL https://sentry.io/get-cli/ | bash
      script:
        - set -e
        - version_file=server/athenian/api/metadata.py
        - current_version=$(grep __version__ $version_file | cut -d\" -f2)
        - sentry-cli releases new -p $SENTRY_PROJECT $current_version
        - sentry-cli releases set-commits --auto $current_version
        - export IMAGE=${GOOGLE_DOCKER_IMAGE}:$current_version
        - make gcloud-login
        - docker load -i $HOME/docker/images.tar || true
        - docker image list
        - docker build --cache-from ${GOOGLE_DOCKER_IMAGE}:latest --build-arg COMMIT=$TRAVIS_COMMIT -t $IMAGE .
        - travis_retry make docker-push
        - make pubsub-publish
        - docker tag $IMAGE ${GOOGLE_DOCKER_IMAGE}
        - IMAGE=${GOOGLE_DOCKER_IMAGE} make docker-push
        - sentry-cli releases finalize $current_version
        - set +e

notifications:
  email: false