language: python
python: 3.7
sudo: true
dist: bionic

env:
  global:
    - GOOGLE_DOCKER_IMAGE=gcr.io/athenian-1/api
    - IMAGE=${GOOGLE_DOCKER_IMAGE}:${TRAVIS_BRANCH}-${TRAVIS_COMMIT:0:7}

cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/google-cloud-sdk/"
    - "$HOME/docker"

before_cache:
  - chown -R travis:travis $HOME/.cache/pip
  - docker save -o $HOME/docker/images.tar ${GOOGLE_DOCKER_IMAGE}:latest

matrix:
  fast_finish: true
  include:
    - install:
        - cd server
        - pip install -r requirements.txt
        - pip install -r lint-requirements.txt
        - pip install -r test-requirements.txt
        - pip install -e .
      script:
        - flake8
        - pytest
    - if: branch != master
      before_install:
        - docker load -i $HOME/docker/images.tar || true
        - docker image list
      install:
        - docker build --cache-from ${GOOGLE_DOCKER_IMAGE} -t ${GOOGLE_DOCKER_IMAGE} .
      script:
        - docker run --rm ${GOOGLE_DOCKER_IMAGE} --help
    - stage: deploy
      if: branch = master AND type != pull_request
      script:
        - docker load -i $HOME/docker/images.tar || true
        - docker tag ${GOOGLE_DOCKER_IMAGE} ${IMAGE}
        - make docker-push

notifications:
  email: false