language: python
python: 3.7
sudo: true
dist: bionic
branches:
  only:
  - master

env:
  global:
    - GOOGLE_DOCKER_IMAGE=gcr.io/athenian-1/api
    - IMAGE_BRANCH_COMMIT=${GOOGLE_DOCKER_IMAGE}:${TRAVIS_COMMIT:0:7}

cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/google-cloud-sdk/"
    - "$HOME/docker"

before_cache:
  - chown -R travis:travis $HOME/.cache/pip
  - docker save -o $HOME/docker/images.tar ${GOOGLE_DOCKER_IMAGE}:latest

stages:
  - main
  - bump-version

matrix:
  fast_finish: true
  include:
    - if: commit_message !~ /Bump version/
      stage: main
      name: Unit tests and style check
      services:
        - memcached
      install:
        - cd server
        - pip install -r requirements.txt
        - pip install -r lint-requirements.txt
        - pip install -r test-requirements.txt
        - pip install -e .
      script:
        - set -e
        - flake8
        - pytest
        - set +e
    - if: commit_message !~ /Bump version/
      stage: main
      name: Docker build smoke test
      before_install:
        - docker load -i $HOME/docker/images.tar || true
        - docker image list
      install:
        - docker build --cache-from ${GOOGLE_DOCKER_IMAGE}:latest --build-arg COMMIT=$TRAVIS_COMMIT -t ${GOOGLE_DOCKER_IMAGE} .
      script:
        - docker run --rm ${GOOGLE_DOCKER_IMAGE} --help
    - if: branch = master AND type != pull_request AND commit_message !~ /Bump version/
      stage: bump-version
      name: Bump the version
      install:
        - git config --global user.name "Groundskeeper Willie"
        - git config --global user.email "bot@athenian.co"
        - pip install bump2version
      script:
        - set -e
        - if git diff --name-only $TRAVIS_BRANCH...HEAD | grep openapi.yaml; then
            version_file=spec/openapi.yaml;
            current_version=$(grep -m1 '^  version:' $version_file | cut -d" " -f4);
            bumpversion --current-version $current_version patch $version_file;
          fi
        - version_file=server/athenian/api/metadata.py
        - current_version=$(grep __version__ $version_file | cut -d\" -f2)
        - bumpversion --tag --current-version $current_version --commit --allow-dirty --commit-args="-a" patch $version_file
        - git remote add gkwillie https://gkwillie:${GKWILLIE_TOKEN}@github.com/$TRAVIS_REPO_SLUG
        - git push --tags gkwillie HEAD:master
        - set +e
    - if: branch IN (master, production) AND type != pull_request AND commit_message =~ /^Bump version/
      stage: main
      name: Deploy
      script:
        - set -e
        - version_file=server/athenian/api/metadata.py
        - current_version=$(grep __version__ $version_file | cut -d\" -f2)
        - export IMAGE=${IMAGE_BRANCH_COMMIT}-$current_version
        - make gcloud-login
        - if [ "${TRAVIS_BRANCH}" = "production" ]; then make pubsub-publish; exit; fi
        - docker load -i $HOME/docker/images.tar || true
        - docker image list
        - docker build --cache-from ${GOOGLE_DOCKER_IMAGE}:latest --build-arg COMMIT=$TRAVIS_COMMIT -t $IMAGE .
        - make docker-push
        - make pubsub-publish
        - docker tag $IMAGE ${GOOGLE_DOCKER_IMAGE}
        - IMAGE=${GOOGLE_DOCKER_IMAGE} make docker-push
        - set +e

notifications:
  email: false