language: python
python: 3.7
sudo: true
dist: bionic
cache:
  pip: true
  directories:
    - $HOME/docker
before_cache:
  - chown -R travis:travis $HOME/.cache/pip
  - docker save -o $HOME/docker/images.tar athenian/api:latest

matrix:
  fast_finish: true
  include:
    - install:
        - cd server
        - pip install -r requirements.txt
        - pip install -r lint-requirements.txt
        - pip install -r test-requirements.txt
        - pip install -e .
      script:
        - flake8
        - pytest
    - before_install:
        - docker load -i $HOME/docker/images.tar || true
        - docker image list
      install:
        - docker build --cache-from athenian/api -t athenian/api .
      script:
        - docker run --rm athenian/api --help

notifications:
  email: false
