language: python
python: 3.7
sudo: true
dist: bionic
cache: pip
before_cache:
  - chown -R travis:travis $HOME/.cache/pip

matrix:
  fast_finish: true
  include:
    - install:
        - cd server
        - pip install -r requirements.txt
        - pip install -r lint-requirements.txt
        - pip install -r test-requirements.txt
        - pip install -e .
      script:
        - flake8
        - pytest
    - install:
        - docker build -t athenian/api .
      script:
        - docker run --rm athenian/api --help

notifications:
  email: false
