comment: false
ignore:
  - server/athenian/api/hacks/reproduce_bug.py
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        informational: true