openapi: 3.0.0
info:
  license:
    name: Proprietary until Eiso decides on licensing
  title: Athenian Dashboard API
  version: 1.0.0
servers:
- url: https://api.athenian.co/v1
paths:
  /metrics_line:
    post:
      operationId: calc_metrics_line
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MetricsRequest'
        description: Desired metric definitions.
        required: true
        x-body-name: body
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalculatedMetrics'
          description: Calculated metrics.
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestError'
          description: The request was invalid.
        422:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoSourceDataError'
          description: No data is available to calculate metrics for the given repositories.
      summary: Calculate metrics.
      x-openapi-router-controller: athenian.api.controllers.metrics_controller
      x-codegen-request-body-name: body
components:
  schemas:
    GenericError:
      type: object
      properties:
        type:
          description: URI reference that identifies the problem type (RFC 7807).
          example: /errors/metrics_line/InvalidRequestError
          type: string
        title:
          description: Short, human-readable summary of the problem type.
          example: Validation failed
          type: string
        status:
          description: Duplicated HTTP status code.
          example: 400
          type: integer
        detail:
          description: Human-readable explanation specific to this occurrence of the problem.
          example: '"pr-slave-time" is not one of [...].'
          type: string
        instance:
          description: URI reference that identifies the specific occurrence of the problem.
          example: https://sentry.io/athenian/api/?query=2763c4eabd7240f59829ee1a02546293
          type: string
      required:
        - type
    InvalidRequestError:
      allOf:
      - $ref: '#/components/schemas/GenericError'
      - type: object
        properties:
          pointer:
            description: Path to the offending request item.
            example: .granularity
            type: string
    NoSourceDataError:
      allOf:
      - $ref: '#/components/schemas/GenericError'
      - type: object
        properties:
          repositories:
            $ref: '#/components/schemas/RepositorySet'
        required:
        - repositories
    MetricID:
      description: Currently supported metric types.
      enum:
      - pr-wip-time
      - pr-wait-first-review-time
      - pr-review-time
      - pr-merging-time
      - pr-release-time
      - pr-lead-time
      example: pr-lead-time
      type: string
    DeveloperID:
      description: |
        User name which uniquely identifies any developer on any service provider.
        The format matches the profile URL without the protocol part.
      example: github.com/vmarkovtsev
      type: string
    RepositoryID:
      description: |
        Repository name which uniquely identifies any repository in any service provider.
        The format matches the repository URL without the protocol part. No ".git" should be appended.
      example: github.com/src-d/go-git
      type: string
    DeveloperSet:
      description: A set of developers. The special value \"all\" denotes everybody.
      example:
      - github.com/vmarkovtsev
      - github.com/mcuadros
      items:
        $ref: '#/components/schemas/DeveloperID'
      type: array
    RepositorySet:
      description: A set of repositories.
      example:
      - github.com/src-d/hercules
      - github.com/athenianco/athenian-api
      items:
        $ref: '#/components/schemas/RepositoryID'
      type: array
    ForSet:
      example:
        repositories:
        - github.com/src-d/hercules
        - github.com/athenianco/athenian-api
        developers:
        - github.com/vmarkovtsev
        - github.com/mcuadros
      properties:
        repositories:
          $ref: '#/components/schemas/RepositorySet'
        developers:
          $ref: '#/components/schemas/DeveloperSet'
      required:
      - repositories
      type: object
    Granularity:
      description: How often the metrics are reported.
      enum:
      - day
      - week
      - month
      type: string
      example: day
    MetricsRequest:
      example:
        for:
        - repositories:
          - github.com/src-d/hercules
          - github.com/athenianco/athenian-api
          developers:
          - github.com/vmarkovtsev
          - github.com/mcuadros
        - repositories:
          - github.com/src-d/hercules
          - github.com/athenianco/athenian-api
          developers:
          - github.com/vmarkovtsev
          - github.com/mcuadros
        metrics:
        - pr-lead-time
        - pr-wip-time
        date_to: 2000-01-23
        date_from: 2000-01-23
        granularity: day
      properties:
        for:
          description: Sets of developers and repositories to calculate the metrics
            for.
          items:
            $ref: '#/components/schemas/ForSet'
          type: array
        metrics:
          description: Requested metric identifiers.
          items:
            $ref: '#/components/schemas/MetricID'
          type: array
        date_from:
          description: The date from when to start measuring the metrics.
          format: date
          type: string
        date_to:
          description: The date up to which to measure the metrics.
          format: date
          type: string
        granularity:
          $ref: '#/components/schemas/Granularity'
      required:
      - date_from
      - date_to
      - for
      - granularity
      - metrics
      type: object
    CalculatedMetric:
      example:
        values:
        - date: 2000-01-23
          values:
          - 0.8008282
          - 0.8008282
          confidence_mins:
          - 0.5
          - 0.5
          confidence_maxs:
          - 1.0
          - 1.0
          confidence_scores:
          - 75
          - 75
        - date: 2000-01-23
          values:
          - 0.8008282
          - 0.8008282
          confidence_mins:
          - 0.5
          - 0.5
          confidence_maxs:
          - 1.0
          - 1.0
          confidence_scores:
          - 75
          - 75
        for:
          repositories:
          - github.com/src-d/hercules
          - github.com/athenianco/athenian-api
          developers:
          - github.com/vmarkovtsev
          - github.com/mcuadros
      properties:
        for:
          $ref: '#/components/schemas/ForSet'
        values:
          items:
            $ref: '#/components/schemas/CalculatedMetric_values'
          type: array
      required:
      - for
      - values
      type: object
    CalculatedMetrics:
      example:
        metrics:
        - pr-lead-time
        - pr-wip-time
        date_to: 2000-01-23
        granularity: day
        calculated:
        - values:
          - date: 2000-01-23
            values:
            - 0.8008282
            - 0.8008282
            confidence_mins:
            - 0.5
            - 0.5
            confidence_maxs:
            - 1.0
            - 1.0
            confidence_scores:
            - 75
            - 75
          - date: 2000-01-23
            values:
            - 0.8008282
            - 0.8008282
            confidence_mins:
            - 0.5
            - 0.5
            confidence_maxs:
            - 1.0
            - 1.0
            confidence_scores:
            - 75
            - 75
          for:
            developers:
            - github.com/vmarkovtsev
            - github.com/mcuadros
            repositories:
            - github.com/src-d/hercules
            - github.com/athenianco/athenian-api
        - values:
          - date: 2000-01-23
            values:
            - 0.8008282
            - 0.8008282
            confidence_mins:
            - 0.5
            - 0.5
            confidence_maxs:
            - 1.0
            - 1.0
            confidence_scores:
            - 75
            - 75
          - date: 2000-01-23
            values:
            - 0.8008282
            - 0.8008282
            confidence_mins:
            - 0.5
            - 0.5
            confidence_maxs:
            - 1.0
            - 1.0
            confidence_scores:
            - 75
            - 75
          for:
            developers:
            - github.com/vmarkovtsev
            - github.com/mcuadros
            repositories:
            - github.com/src-d/hercules
            - github.com/athenianco/athenian-api
        date_from: 2000-01-23
      properties:
        calculated:
          description: The values of the requested metrics through time.
          items:
            $ref: '#/components/schemas/CalculatedMetric'
          type: array
        metrics:
          description: Repeats `MetricsRequest.metrics`.
          items:
            $ref: '#/components/schemas/MetricID'
          type: array
        date_from:
          description: Repeats `MetricsRequest.date_from`.
          format: date
          type: string
        date_to:
          description: Repeats `MetricsRequest.date_to`.
          format: date
          type: string
        granularity:
          $ref: '#/components/schemas/Granularity'
      required:
      - calculated
      - date_from
      - date_to
      - granularity
      - metrics
      type: object
    CalculatedMetric_values:
      example:
        date: 2000-01-23
        values:
        - 0.8008282
        - 0.8008282
        confidence_mins:
        - 0.5
        - 0.5
        confidence_maxs:
        - 1.0
        - 1.0
        confidence_scores:
        - 75
        - 75
      properties:
        date:
          description: Where you should relate the metric value to on the time axis.
          format: date
          type: string
        values:
          description: The same order as `metrics`.
          items:
            format: float
            type: number
          type: array
        confidence_mins:
          description: Confidence interval @ p=0.95, minimum. The same order as `metrics`.
          items:
            format: float
            type: number
          type: array
        confidence_maxs:
          description: Confidence interval @ p=0.95, maximum. The same order as `metrics`.
          items:
            format: float
            type: number
          type: array
        confidence_scores:
          description: Confidence score from 0 (no idea) to 100 (very confident). The same order as `metrics`.
          items:
            type: integer
          type: array
      required:
      - date
      - values
      - confidence_scores
