openapi: 3.0.0
info:
  license:
    name: Proprietary until Eiso decides on licensing
  title: Athenian Dashboard API
  version: 1.0.0
servers:
- url: https://api.athenian.co/v1
paths:
  /metrics_line:
    post:
      operationId: calc_metrics_line
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MetricsRequest'
        description: Desired metric definitions.
        required: true
        x-body-name: body
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalculatedMetrics'
          description: Calculated metrics.
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestError'
          description: The request was invalid.
        422:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoSourceDataError'
          description: No data is available to calculate metrics for the given repositories.
      summary: Calculate metrics.
      x-openapi-router-controller: athenian.api.controllers.metrics_controller
      x-codegen-request-body-name: body
  /reposet/create:
    post:
      operationId: create_reposet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RepositorySet'
        x-body-name: body
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatedIdentifier'
          description: Identifier of the created repository set.
        403:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: The user is forbidden to create a repository set from the specified
            items.
      summary: Create a repository set.
      x-openapi-router-controller: athenian.api.controllers.reposet_controller
      x-codegen-request-body-name: body
  /reposet/{id}:
    delete:
      operationId: delete_reposet
      parameters:
      - description: Numeric identifier of the repository set to list.
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
          description: Empty object indicates a successful removal.
        403:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: The user is forbidden to delete the specified repository set.
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: The specified repository set was not found.
      summary: Delete a repository set.
      x-openapi-router-controller: athenian.api.controllers.reposet_controller
      x-codegen-request-body-name: body
    get:
      operationId: get_reposet
      parameters:
      - description: Numeric identifier of the repository set to list.
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RepositorySet'
          description: List of repositories in the specified set.
        403:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: The user is forbidden to list the specified repository set.
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: The specified repository set was not found.
      summary: List a repository set.
      x-openapi-router-controller: athenian.api.controllers.reposet_controller
      x-codegen-request-body-name: body
    put:
      operationId: update_reposet
      parameters:
      - description: Numeric identifier of the repository set to list.
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RepositorySet'
        x-body-name: body
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
          description: Empty object indicates a successful operation.
        403:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: The user is forbidden to update the specified repository set.
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: The specified repository set was not found.
      summary: Update a repository set.
      x-openapi-router-controller: athenian.api.controllers.reposet_controller
      x-codegen-request-body-name: body
  /reposets:
    get:
      operationId: list_reposets
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RepositorySetList'
          description: List the repository sets belonging to the current user.
      summary: List the repository sets belonging to the current user.
      x-openapi-router-controller: athenian.api.controllers.reposet_controller
      x-codegen-request-body-name: body
components:
  schemas:
    CreatedIdentifier:
      example:
        id: 777
      properties:
        id:
          description: Identifier of the created entity.
          example: 777
          type: integer
      required:
      - id
      type: object
    GenericError:
      properties:
        type:
          description: URI reference that identifies the problem type (RFC 7807).
          example: /errors/metrics_line/InvalidRequestError
          type: string
        title:
          description: Short, human-readable summary of the problem type.
          example: Validation failed
          type: string
        status:
          description: Duplicated HTTP status code.
          example: 400
          type: integer
        detail:
          description: Human-readable explanation specific to this occurrence of the
            problem.
          example: '"pr-slave-time" is not one of [...].'
          type: string
        instance:
          description: URI reference that identifies the specific occurrence of the
            problem.
          example: https://sentry.io/athenian/api/?query=2763c4eabd7240f59829ee1a02546293
          type: string
      required:
      - title
      - type
      type: object
    InvalidRequestError:
      allOf:
      - $ref: '#/components/schemas/GenericError'
      - type: object
        properties:
          pointer:
            description: Path to the offending request item.
            example: .granularity
            type: string
    NoSourceDataError:
      allOf:
      - $ref: '#/components/schemas/GenericError'
      - type: object
        properties:
          repositories:
            $ref: '#/components/schemas/RepositorySet'
        required:
        - repositories
    MetricID:
      description: Currently supported metric types.
      enum:
      - pr-wip-time
      - pr-wait-first-review-time
      - pr-review-time
      - pr-merging-time
      - pr-release-time
      - pr-lead-time
      example: pr-lead-time
      type: string
    DeveloperID:
      description: |
        User name which uniquely identifies any developer on any service provider.
        The format matches the profile URL without the protocol part.
      example: github.com/vmarkovtsev
      type: string
    RepositoryID:
      description: |
        Repository name which uniquely identifies any repository in any service provider.
        The format matches the repository URL without the protocol part. No ".git" should be appended.
        We support a special syntax for repository sets: "{reposet id}" adds all the repositories
        from the given set.
      example: github.com/src-d/go-git
      type: string
    DeveloperSet:
      description: A set of developers. An empty list disables the filter and includes
        everybody. Duplicates are automatically ignored.
      example:
      - github.com/vmarkovtsev
      - github.com/mcuadros
      items:
        $ref: '#/components/schemas/DeveloperID'
      type: array
    RepositorySet:
      description: A set of repositories. An empty list results an empty response
        in contrary to DeveloperSet. Duplicates are automatically ignored.
      example:
      - github.com/src-d/hercules
      - github.com/athenianco/athenian-api
      items:
        $ref: '#/components/schemas/RepositoryID'
      type: array
    RepositorySetList:
      description: List of repository sets owned by a user.
      items:
        $ref: '#/components/schemas/RepositorySetListItem'
      type: array
    RepositorySetListItem:
      description: Element of RepositorySetList.
      properties:
        id:
          description: Repository set identifier.
          type: integer
        created:
          description: Date and time of creation of the repository set.
          format: date-item
          type: string
        updated:
          description: Date and time of the last change of the repository set.
          format: date-item
          type: string
        items_count:
          description: Number of repositories in the set.
          type: integer
      type: object
    ForSet:
      example:
        repositories:
        - github.com/src-d/hercules
        - github.com/athenianco/athenian-api
        developers:
        - github.com/vmarkovtsev
        - github.com/mcuadros
      properties:
        repositories:
          $ref: '#/components/schemas/RepositorySet'
        developers:
          $ref: '#/components/schemas/DeveloperSet'
      required:
      - repositories
      type: object
    Granularity:
      description: How often the metrics are reported.
      enum:
      - day
      - week
      - month
      example: day
      type: string
    MetricsRequest:
      example:
        for:
        - repositories:
          - github.com/src-d/hercules
          - github.com/athenianco/athenian-api
          developers:
          - github.com/vmarkovtsev
          - github.com/mcuadros
        - repositories:
          - github.com/src-d/hercules
          - github.com/athenianco/athenian-api
          developers:
          - github.com/vmarkovtsev
          - github.com/mcuadros
        metrics:
        - pr-lead-time
        - pr-wip-time
        date_from: 2000-01-23
        date_to: 2020-01-23
        granularity: day
      properties:
        for:
          description: Sets of developers and repositories to calculate the metrics
            for.
          items:
            $ref: '#/components/schemas/ForSet'
          type: array
        metrics:
          description: Requested metric identifiers.
          items:
            $ref: '#/components/schemas/MetricID'
          type: array
        date_from:
          description: The date from when to start measuring the metrics.
          format: date
          type: string
        date_to:
          description: The date up to which to measure the metrics.
          format: date
          type: string
        granularity:
          $ref: '#/components/schemas/Granularity'
      required:
      - date_from
      - date_to
      - for
      - granularity
      - metrics
      type: object
    CalculatedMetric:
      example:
        values:
        - date: 2000-01-23
          values:
          - 0.8008282
          - 0.8008282
          confidence_mins:
          - 0.5
          - 0.5
          confidence_maxs:
          - 1.0
          - 1.0
          confidence_scores:
          - 75
          - 75
        - date: 2000-01-23
          values:
          - 0.8008282
          - 0.8008282
          confidence_mins:
          - 0.5
          - 0.5
          confidence_maxs:
          - 1.0
          - 1.0
          confidence_scores:
          - 75
          - 75
        for:
          repositories:
          - github.com/src-d/hercules
          - github.com/athenianco/athenian-api
          developers:
          - github.com/vmarkovtsev
          - github.com/mcuadros
      properties:
        for:
          $ref: '#/components/schemas/ForSet'
        values:
          items:
            $ref: '#/components/schemas/CalculatedMetric_values'
          type: array
      required:
      - for
      - values
      type: object
    CalculatedMetrics:
      example:
        metrics:
        - pr-lead-time
        - pr-wip-time
        date_from: 2000-01-23
        granularity: day
        calculated:
        - values:
          - date: 2000-01-23
            values:
            - 0.8008282
            - 0.8008282
            confidence_mins:
            - 0.5
            - 0.5
            confidence_maxs:
            - 1.0
            - 1.0
            confidence_scores:
            - 75
            - 75
          - date: 2000-01-23
            values:
            - 0.8008282
            - 0.8008282
            confidence_mins:
            - 0.5
            - 0.5
            confidence_maxs:
            - 1.0
            - 1.0
            confidence_scores:
            - 75
            - 75
          for:
            developers:
            - github.com/vmarkovtsev
            - github.com/mcuadros
            repositories:
            - github.com/src-d/hercules
            - github.com/athenianco/athenian-api
        - values:
          - date: 2000-01-23
            values:
            - 0.8008282
            - 0.8008282
            confidence_mins:
            - 0.5
            - 0.5
            confidence_maxs:
            - 1.0
            - 1.0
            confidence_scores:
            - 75
            - 75
          - date: 2000-01-23
            values:
            - 0.8008282
            - 0.8008282
            confidence_mins:
            - 0.5
            - 0.5
            confidence_maxs:
            - 1.0
            - 1.0
            confidence_scores:
            - 75
            - 75
          for:
            developers:
            - github.com/vmarkovtsev
            - github.com/mcuadros
            repositories:
            - github.com/src-d/hercules
            - github.com/athenianco/athenian-api
        date_to: 2020-01-23
      properties:
        calculated:
          description: The values of the requested metrics through time. The sequence
            order is not guaranteed to be the same as in the preceding request.
          items:
            $ref: '#/components/schemas/CalculatedMetric'
          type: array
        metrics:
          description: Repeats `MetricsRequest.metrics`.
          items:
            $ref: '#/components/schemas/MetricID'
          type: array
        date_from:
          description: Repeats `MetricsRequest.date_from`.
          format: date
          type: string
        date_to:
          description: Repeats `MetricsRequest.date_to`.
          format: date
          type: string
        granularity:
          $ref: '#/components/schemas/Granularity'
      required:
      - calculated
      - date_from
      - date_to
      - granularity
      - metrics
      type: object
    CalculatedMetric_values:
      example:
        date: 2000-01-23
        values:
        - 0.8008282
        - 0.8008282
        confidence_mins:
        - 0.5
        - 0.5
        confidence_maxs:
        - 1.0
        - 1.0
        confidence_scores:
        - 75
        - 75
      properties:
        date:
          description: Where you should relate the metric value to on the time axis.
          format: date
          type: string
        values:
          description: The same order as `metrics`.
          items:
            format: float
            type: number
          type: array
        confidence_mins:
          description: Confidence interval @ p=0.95, minimum. The same order as `metrics`.
            It is optional because there can be exact metrics like "count open PRs
            per month".
          items:
            format: float
            type: number
          type: array
        confidence_maxs:
          description: Confidence interval @ p=0.95, maximum. The same order as `metrics`.
            It is optional because there can be exact metrics like "count open PRs
            per month".
          items:
            format: float
            type: number
          type: array
        confidence_scores:
          description: Confidence score from 0 (no idea) to 100 (very confident).
            The same order as `metrics`.
          items:
            type: integer
          type: array
      required:
      - confidence_scores
      - date
      - values
