from athenian.api import serialization
from athenian.api.models.web.base_model_ import Model


class AcceptedInvitation(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, origin: str = None):
        """AcceptedInvitation - a model defined in OpenAPI

        :param origin: The origin of this AcceptedInvitation.
        """
        self.openapi_types = {"origin": str}

        self.attribute_map = {"origin": "origin"}

        self._origin = origin

    @classmethod
    def from_dict(cls, dikt: dict) -> "AcceptedInvitation":
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The AcceptedInvitation of this AcceptedInvitation.
        """
        return serialization.deserialize_model(dikt, cls)

    @property
    def origin(self) -> str:
        """Gets the origin of this AcceptedInvitation.

        Invitation URL.

        :return: The origin of this AcceptedInvitation.
        """
        return self._origin

    @origin.setter
    def origin(self, origin: str):
        """Sets the origin of this AcceptedInvitation.

        Invitation URL.

        :param origin: The origin of this AcceptedInvitation.
        """
        if origin is None:
            raise ValueError("Invalid value for `origin`, must not be `None`")

        self._origin = origin
