from typing import List, Optional, TypeVar

from athenian.api.models.web.base_model_ import Model
from athenian.api.models.web.jira_filter import JIRAFilter
from athenian.api.models.web.pull_request_with import PullRequestWith


ForSetLike = TypeVar("ForSetLike", bound=Model)


class RepositoryGroupsMixin:
    """ForSet mixin to add support for `repogroups`."""

    @property
    def repogroups(self) -> Optional[List[List[int]]]:
        """Gets the repogroups of this ForSet.

        :return: The repogroups of this ForSet.
        """
        return self._repogroups

    @repogroups.setter
    def repogroups(self, repogroups: Optional[List[List[int]]]):
        """Sets the repogroups of this ForSet.

        :param repogroups: The repogroups of this ForSet.
        """
        if repogroups is not None:
            if len(repogroups) == 0:
                raise ValueError("`repogroups` must contain at least one list")
            for i, group in enumerate(repogroups):
                if len(group) == 0:
                    raise ValueError("`repogroups[%d]` must contain at least one element" % i)
                for j, v in enumerate(group):
                    if v < 0:
                        raise ValueError(
                            "`repogroups[%d][%d]` = %s must not be negative" % (i, j, v))
                    if self._repositories is not None and v >= len(self._repositories):
                        raise ValueError(
                            "`repogroups[%d][%d]` = %s must be less than the number of "
                            "repositories (%d)" % (i, j, v, len(self._repositories)))
                if len(set(group)) < len(group):
                    raise ValueError("`repogroups[%d]` has duplicate items" % i)

        self._repogroups = repogroups

    def select_repogroup(self: ForSetLike, index: int) -> ForSetLike:
        """Change `repositories` to point at the specified group and clear `repogroups`."""
        fs = self.copy()
        if self.repogroups is None:
            if index > 0:
                raise IndexError("%d is out of range (no repogroups)" % index)
            return fs
        if index >= len(self.repogroups):
            raise IndexError("%d is out of range (max is %d)" % (index, len(self.repogroups)))
        fs.repogroups = None
        fs.repositories = [self.repositories[i] for i in self.repogroups[index]]
        return fs


class ForSet(Model, RepositoryGroupsMixin):
    """This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)."""

    openapi_types = {
        "repositories": List[str],
        "repogroups": Optional[List[List[int]]],
        "with_": Optional[PullRequestWith],
        "withgroups": Optional[List[PullRequestWith]],
        "labels_include": Optional[List[str]],
        "labels_exclude": Optional[List[str]],
        "jira": Optional[JIRAFilter],
        "lines": Optional[List[int]],
    }

    attribute_map = {
        "repositories": "repositories",
        "repogroups": "repogroups",
        "with_": "with",
        "withgroups": "withgroups",
        "labels_include": "labels_include",
        "labels_exclude": "labels_exclude",
        "jira": "jira",
        "lines": "lines",
    }

    def __init__(
        self,
        repositories: Optional[List[str]] = None,
        repogroups: Optional[List[List[int]]] = None,
        with_: Optional[PullRequestWith] = None,
        withgroups: Optional[List[PullRequestWith]] = None,
        labels_include: Optional[List[str]] = None,
        labels_exclude: Optional[List[str]] = None,
        jira: Optional[JIRAFilter] = None,
        lines: Optional[List[int]] = None,
    ):
        """ForSet - a model defined in OpenAPI

        :param repositories: The repositories of this ForSet.
        :param repogroups: The repogroups of this ForSet.
        :param with_: The with of this ForSet.
        :param withgroups: The withgroups of this ForSet.
        :param labels_include: The labels_include of this ForSet.
        :param labels_exclude: The labels_exclude of this ForSet.
        :param jira: The jira of this ForSet.
        :param lines: The lines of this ForSet.
        """
        self._repositories = repositories
        self._repogroups = repogroups
        self._with_ = with_
        self._withgroups = withgroups
        self._labels_include = labels_include
        self._labels_exclude = labels_exclude
        self._jira = jira
        self._lines = lines

    @property
    def repositories(self) -> List[str]:
        """Gets the repositories of this ForSet.

        :return: The repositories of this ForSet.
        """
        return self._repositories

    @repositories.setter
    def repositories(self, repositories: List[str]):
        """Sets the repositories of this ForSet.

        :param repositories: The repositories of this ForSet.
        """
        if repositories is None:
            raise ValueError("Invalid value for `repositories`, must not be `None`")
        if self._repogroups is not None:
            for i, group in enumerate(self._repogroups):
                for j, v in enumerate(group):
                    if v >= len(repositories):
                        raise ValueError(
                            "`repogroups[%d][%d]` = %s must be less than the number of "
                            "repositories (%d)" % (i, j, v, len(repositories)))

        self._repositories = repositories

    @property
    def with_(self) -> Optional[PullRequestWith]:
        """Gets the with_ of this PullRequest.

        List of developers related to this PR.

        :return: The with_ of this PullRequest.
        """
        return self._with_

    @with_.setter
    def with_(self, with_: Optional[PullRequestWith]):
        """Sets the with_ of this PullRequest.

        List of developers related to this PR.

        :param with_: The with_ of this PullRequest.
        """
        self._with_ = with_

    @property
    def withgroups(self) -> Optional[List[PullRequestWith]]:
        """Gets the withgroups of this PullRequest.

        List of developers related to this PR.

        :return: The withgroups of this PullRequest.
        """
        return self._withgroups

    @withgroups.setter
    def withgroups(self, withgroups: Optional[List[PullRequestWith]]):
        """Sets the withgroups of this PullRequest.

        List of developers related to this PR.

        :param withgroups: The withgroups of this PullRequest.
        """
        self._withgroups = withgroups

    @property
    def labels_include(self) -> Optional[List[str]]:
        """Gets the labels_include of this ForSet.

        :return: The labels_include of this ForSet.
        """
        return self._labels_include

    @labels_include.setter
    def labels_include(self, labels_include: Optional[List[str]]):
        """Sets the labels_include of this ForSet.

        :param labels_include: The labels_include of this ForSet.
        """
        self._labels_include = labels_include

    @property
    def labels_exclude(self) -> Optional[List[str]]:
        """Gets the labels_exclude of this ForSet.

        :return: The labels_exclude of this ForSet.
        """
        return self._labels_exclude

    @labels_exclude.setter
    def labels_exclude(self, labels_exclude: Optional[List[str]]):
        """Sets the labels_exclude of this ForSet.

        :param labels_exclude: The labels_exclude of this ForSet.
        """
        self._labels_exclude = labels_exclude

    @property
    def jira(self) -> Optional[JIRAFilter]:
        """Gets the jira of this ForSet.

        :return: The jira of this ForSet.
        """
        return self._jira

    @jira.setter
    def jira(self, jira: Optional[JIRAFilter]):
        """Sets the jira of this ForSet.

        :param jira: The jira of this ForSet.
        """
        self._jira = jira

    @property
    def lines(self) -> Optional[List[int]]:
        """Gets the lines of this ForSet.

        :return: The lines of this ForSet.
        """
        return self._lines

    @lines.setter
    def lines(self, lines: Optional[List[int]]):
        """Sets the lines of this ForSet.

        :param lines: The lines of this ForSet.
        """
        if lines is not None:
            if len(lines) < 2:
                raise ValueError("`lines` must contain at least 2 elements")
            if lines[0] < 0:
                raise ValueError("all elements of `lines` must be non-negative")
            for i, val in enumerate(lines[:-1]):
                if val >= lines[i + 1]:
                    raise ValueError("`lines` must monotonically increase")
        self._lines = lines

    def select_lines(self, index: int) -> "ForSet":
        """Change `lines` to point at the specified line range."""
        fs = self.copy()
        if self.lines is None:
            if index > 0:
                raise IndexError("%d is out of range (no lines)" % index)
            return fs
        if index >= len(self.lines) - 1:
            raise IndexError("%d is out of range (max is %d)" % (index, len(self.lines) - 1))
        fs.lines = [fs.lines[index], fs.lines[index + 1]]
        return fs
