from typing import List, Optional

from athenian.api.models.web.base_model_ import AllOf, Model
from athenian.api.models.web.for_set_common import CommonPullRequestFilters, ForSetLines
from athenian.api.models.web.pull_request_with import PullRequestWith


class _ForSetPullRequests(Model, sealed=False):
    """This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)."""

    with_: (Optional[PullRequestWith], "with")
    withgroups: Optional[List[PullRequestWith]]
    environments: Optional[List[str]]

    def select_withgroup(self, index: int) -> "ForSetPullRequests":
        """Change `with` to point at the specified `withgroup`."""
        fs = self.copy()
        if self.withgroups is None:
            if index > 0:
                raise IndexError("%d is out of range (no withgroups)" % index)
            return fs
        if index >= len(self.withgroups):
            raise IndexError("%d is out of range (max is %d)" % (index, len(self.withgroups) - 1))
        fs.with_ = self.withgroups[index]
        fs.withgroups = None
        return fs


ForSetPullRequests = AllOf(
    _ForSetPullRequests,
    ForSetLines,
    CommonPullRequestFilters,
    name="ForSetPullRequests",
    module=__name__,
)
