from http import HTTPStatus

from athenian.api.models.web.generic_error import GenericError


class InvalidRequestError(GenericError):
    """This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)."""

    def __init__(
        self,
        pointer: str,
        title: str = HTTPStatus.BAD_REQUEST.phrase,
        status: int = HTTPStatus.BAD_REQUEST,
        detail: str = None,
        instance: str = None,
    ):
        """InvalidRequestError - a model defined in OpenAPI

        :param title: The title of this InvalidRequestError.
        :param status: The status of this InvalidRequestError.
        :param detail: The detail of this InvalidRequestError.
        :param instance: The instance of this InvalidRequestError.
        :param pointer: The pointer of this InvalidRequestError.
        """
        super().__init__(type="/errors/InvalidRequestError", title=title, status=status,
                         detail=detail, instance=instance)
        self.openapi_types.update({
            "pointer": str,
        })

        self.attribute_map.update({
            "pointer": "pointer",
        })

        self._pointer = pointer

    @property
    def pointer(self):
        """Gets the pointer of this InvalidRequestError.

        Path to the offending request item.

        :return: The pointer of this InvalidRequestError.
        :rtype: str
        """
        return self._pointer

    @pointer.setter
    def pointer(self, pointer):
        """Sets the pointer of this InvalidRequestError.

        Path to the offending request item.

        :param pointer: The pointer of this InvalidRequestError.
        :type pointer: str
        """
        if pointer is None:
            raise ValueError("Invalid value for `pointer`, must not be `None`")

        self._pointer = pointer
