from athenian.api.models.web.base_model_ import Model
from athenian.api.models.web.user import User


class InvitedUser(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    account: int
    user: User
