# coding: utf-8

from athenian.api import serialization
from athenian.api.models.web.base_model_ import Model


class MetricID(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    PR_WIP_TIME = "pr-wip-time"
    PR_WAIT_FIRST_REVIEW_TIME = "pr-wait-first-review-time"
    PR_REVIEW_TIME = "pr-review-time"
    PR_MERGING_TIME = "pr-merging-time"
    PR_RELEASE_TIME = "pr-release-time"
    PR_LEAD_TIME = "pr-lead-time"

    def __init__(self):
        """MetricID - a model defined in OpenAPI"""
        self.openapi_types = {}

        self.attribute_map = {}

    @classmethod
    def from_dict(cls, dikt: dict) -> "MetricID":
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The MetricID of this MetricID.
        """
        return serialization.deserialize_model(dikt, cls)
