from datetime import date, datetime
from typing import List

from athenian.api.models.web.base_model_ import Model
from athenian.api.models.web.for_set import ForSet
from athenian.api.models.web.metric_id import MetricID


class MetricsRequest(Model):
    """This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)."""

    def __init__(
        self,
        _for: List[ForSet] = None,
        metrics: List[MetricID] = None,
        date_from: date = None,
        date_to: date = None,
        granularity: str = None,
        account: int = None,
    ):
        """MetricsRequest - a model defined in OpenAPI

        :param _for: The _for of this MetricsRequest.
        :param metrics: The metrics of this MetricsRequest.
        :param date_from: The date_from of this MetricsRequest.
        :param date_to: The date_to of this MetricsRequest.
        :param granularity: The granularity of this MetricsRequest.
        :param account: The account of this MetricsRequest.
        """
        self.openapi_types = {
            "_for": List[ForSet],
            "metrics": List[MetricID],
            "date_from": date,
            "date_to": date,
            "granularity": str,
            "account": int,
        }

        self.attribute_map = {
            "_for": "for",
            "metrics": "metrics",
            "date_from": "date_from",
            "date_to": "date_to",
            "granularity": "granularity",
            "account": "account",
        }

        self.__for = _for
        self._metrics = metrics
        self._date_from = date_from
        self._date_to = date_to
        self._granularity = granularity
        self._account = account

    @property
    def _for(self) -> List[ForSet]:
        """Gets the _for of this MetricsRequest.

        Sets of developers and repositories to calculate the metrics for.

        :return: The _for of this MetricsRequest.
        """
        return self.__for

    @_for.setter
    def _for(self, _for: List[ForSet]):
        """Sets the _for of this MetricsRequest.

        Sets of developers and repositories to calculate the metrics for.

        :param _for: The _for of this MetricsRequest.
        """
        if _for is None:
            raise ValueError("Invalid value for `_for`, must not be `None`")

        self.__for = _for

    @property
    def metrics(self) -> List[MetricID]:
        """Gets the metrics of this MetricsRequest.

        Requested metric identifiers.

        :return: The metrics of this MetricsRequest.
        """
        return self._metrics

    @metrics.setter
    def metrics(self, metrics: List[MetricID]):
        """Sets the metrics of this MetricsRequest.

        Requested metric identifiers.

        :param metrics: The metrics of this MetricsRequest.
        """
        if metrics is None:
            raise ValueError("Invalid value for `metrics`, must not be `None`")

        self._metrics = metrics

    @property
    def date_from(self) -> date:
        """Gets the date_from of this MetricsRequest.

        The date from when to start measuring the metrics.

        :return: The date_from of this MetricsRequest.
        """
        return self._date_from

    @date_from.setter
    def date_from(self, date_from: date):
        """Sets the date_from of this MetricsRequest.

        The date from when to start measuring the metrics.

        :param date_from: The date_from of this MetricsRequest.
        """
        if date_from is None:
            raise ValueError("Invalid value for `date_from`, must not be `None`")

        if isinstance(date_from, datetime):
            date_from = date_from.date()
        self._date_from = date_from

    @property
    def date_to(self) -> date:
        """Gets the date_to of this MetricsRequest.

        The date up to which to measure the metrics.

        :return: The date_to of this MetricsRequest.
        """
        return self._date_to

    @date_to.setter
    def date_to(self, date_to: date):
        """Sets the date_to of this MetricsRequest.

        The date up to which to measure the metrics.

        :param date_to: The date_to of this MetricsRequest.
        """
        if date_to is None:
            raise ValueError("Invalid value for `date_to`, must not be `None`")

        if isinstance(date_to, datetime):
            date_to = date_to.date()
        self._date_to = date_to

    @property
    def granularity(self) -> str:
        """Gets the granularity of this MetricsRequest.

        :return: The granularity of this MetricsRequest.
        """
        return self._granularity

    @granularity.setter
    def granularity(self, granularity: str):
        """Sets the granularity of this MetricsRequest.

        :param granularity: The granularity of this MetricsRequest.
        """
        if granularity is None:
            raise ValueError("Invalid value for `granularity`, must not be `None`")

        self._granularity = granularity

    @property
    def account(self) -> int:
        """Gets the account of this MetricsRequest.

        :return: The account of this MetricsRequest.
        """
        return self._account

    @account.setter
    def account(self, account: int):
        """Sets the account of this MetricsRequest.

        :param account: The account of this MetricsRequest.
        """
        if account is None:
            raise ValueError("Invalid value for `account`, must not be `None`")

        self._account = account
