from athenian.api.models.web.base_model_ import Model


class MetricID(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    PR_WIP_TIME = "pr-wip-time"
    PR_REVIEW_TIME = "pr-review-time"
    PR_MERGING_TIME = "pr-merging-time"
    PR_RELEASE_TIME = "pr-release-time"
    PR_LEAD_TIME = "pr-lead-time"
    ALL = {
        PR_WIP_TIME,
        PR_REVIEW_TIME,
        PR_MERGING_TIME,
        PR_RELEASE_TIME,
        PR_LEAD_TIME,
    }

    def __init__(self):
        """MetricID - a model defined in OpenAPI"""
        self.openapi_types = {}

        self.attribute_map = {}
