# coding: utf-8
from http import HTTPStatus
from typing import List

from athenian.api.models.web.generic_error import GenericError
from athenian.api.models.web.repository_set import RepositorySet


class NoSourceDataError(GenericError):
    """This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)."""

    def __init__(
        self,
        repositories: List[str],
        title: str = HTTPStatus.UNPROCESSABLE_ENTITY.phrase,
        status: int = None,
        detail: str = None,
        instance: str = None,
    ):
        """NoSourceDataError - a model defined in OpenAPI

        :param title: The title of this NoSourceDataError.
        :param status: The status of this NoSourceDataError.
        :param detail: The detail of this NoSourceDataError.
        :param instance: The instance of this NoSourceDataError.
        :param repositories: The repositories of this NoSourceDataError.
        """
        super().__init__(type="/errors/NoSourceDataError", title=title, status=status,
                         detail=detail, instance=instance)
        self.openapi_types.update({
            "repositories": RepositorySet,
        })

        self.attribute_map.update({
            "repositories": "repositories",
        })

        self._repositories = repositories

    @property
    def repositories(self):
        """Gets the repositories of this NoSourceDataError.

        :return: The repositories of this NoSourceDataError.
        :rtype: RepositorySet
        """
        return self._repositories

    @repositories.setter
    def repositories(self, repositories):
        """Sets the repositories of this NoSourceDataError.

        :param repositories: The repositories of this NoSourceDataError.
        :type repositories: RepositorySet
        """
        if repositories is None:
            raise ValueError("Invalid value for `repositories`, must not be `None`")

        self._repositories = repositories
