from http import HTTPStatus

from athenian.api.models.web.generic_error import GenericError


class NoSourceDataError(GenericError):
    """This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)."""

    def __init__(
        self,
        title: str = HTTPStatus.UNPROCESSABLE_ENTITY.phrase,
        status: int = HTTPStatus.UNPROCESSABLE_ENTITY,
        detail: str = None,
    ):
        """NoSourceDataError - a model defined in OpenAPI

        :param title: The title of this NoSourceDataError.
        :param status: The status of this NoSourceDataError.
        :param detail: The detail of this NoSourceDataError.
        :param instance: The instance of this NoSourceDataError.
        """
        super().__init__(
            type="/errors/NoSourceDataError", title=title, status=status, detail=detail,
        )
