from athenian.api import serialization
from athenian.api.models.web.base_model_ import Model


class PullRequestPipelineStage(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    WIP = "wip"
    REVIEW = "review"
    MERGE = "merge"
    RELEASE = "release"
    GOLD = "gold"
    ALL = {WIP, REVIEW, MERGE, RELEASE, GOLD}

    def __init__(self):
        """PullRequestPipelineStage - a model defined in OpenAPI."""
        self.openapi_types = {}

        self.attribute_map = {}

    @classmethod
    def from_dict(cls, dikt: dict) -> "PullRequestPipelineStage":
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The PullRequestPipelineStage of this PullRequestPipelineStage.
        """
        return serialization.deserialize_model(dikt, cls)
