from athenian.api.models.web.base_model_ import Enum, Model


class PullRequestPipelineStage(Model, metaclass=Enum):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    WIP = "wip"
    REVIEW = "review"
    MERGE = "merge"
    RELEASE = "release"
    DONE = "done"
