from athenian.api.models.web.base_model_ import Enum, Model


class PullRequestMetricID(Model, metaclass=Enum):
    """Linear PR metric identifier."""

    PR_WIP_TIME = "pr-wip-time"
    PR_WIP_PENDING_COUNT = "pr-wip-pending-count"
    PR_WIP_COUNT = "pr-wip-count"
    PR_WIP_COUNT_Q = "pr-wip-count-q"
    PR_REVIEW_TIME = "pr-review-time"
    PR_REVIEW_PENDING_COUNT = "pr-review-pending-count"
    PR_REVIEW_COUNT = "pr-review-count"
    PR_REVIEW_COUNT_Q = "pr-review-count-q"
    PR_MERGING_TIME = "pr-merging-time"
    PR_MERGING_PENDING_COUNT = "pr-merging-pending-count"
    PR_MERGING_COUNT = "pr-merging-count"
    PR_MERGING_COUNT_Q = "pr-merging-count-q"
    PR_RELEASE_TIME = "pr-release-time"
    PR_RELEASE_PENDING_COUNT = "pr-release-pending-count"
    PR_RELEASE_COUNT = "pr-release-count"
    PR_RELEASE_COUNT_Q = "pr-release-count-q"
    PR_LEAD_TIME = "pr-lead-time"
    PR_LEAD_COUNT = "pr-lead-count"
    PR_LEAD_COUNT_Q = "pr-lead-count-q"
    PR_CYCLE_TIME = "pr-cycle-time"
    PR_CYCLE_COUNT = "pr-cycle-count"
    PR_CYCLE_COUNT_Q = "pr-cycle-count-q"
    PR_ALL_COUNT = "pr-all-count"
    PR_FLOW_RATIO = "pr-flow-ratio"
    PR_OPENED = "pr-opened"
    PR_REVIEWED = "pr-reviewed"
    PR_NOT_REVIEWED = "pr-not-reviewed"
    PR_MERGED = "pr-merged"
    PR_REJECTED = "pr-rejected"
    PR_CLOSED = "pr-closed"
    PR_DONE = "pr-done"
    PR_WAIT_FIRST_REVIEW_TIME = "pr-wait-first-review-time"
    PR_WAIT_FIRST_REVIEW_COUNT = "pr-wait-first-review-count"
    PR_WAIT_FIRST_REVIEW_COUNT_Q = "pr-wait-first-review-count-q"
    PR_SIZE = "pr-size"
    PR_OPENED_MAPPED_TO_JIRA = "pr-opened-mapped-to-jira"
    PR_DONE_MAPPED_TO_JIRA = "pr-done-mapped-to-jira"
    PR_ALL_MAPPED_TO_JIRA = "pr-all-mapped-to-jira"
