from athenian.api.models.web.base_model_ import Model


class PullRequestPipelineStage(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    WIP = "wip"
    REVIEW = "review"
    MERGE = "merge"
    RELEASE = "release"
    DONE = "done"
    ALL = {WIP, REVIEW, MERGE, RELEASE, DONE}

    def __init__(self):
        """PullRequestPipelineStage - a model defined in OpenAPI."""
        self.openapi_types = {}

        self.attribute_map = {}
