from athenian.api.models.web.base_model_ import Enum, Model


class ReleaseMetricID(Model, metaclass=Enum):
    """Linear release metric identifier."""

    RELEASE_COUNT = "release-count"
    TAG_RELEASE_COUNT = "release-tag-count"
    BRANCH_RELEASE_COUNT = "release-branch-count"
    RELEASE_PRS = "release-prs"
    TAG_RELEASE_PRS = "release-tag-prs"
    BRANCH_RELEASE_PRS = "release-branch-prs"
    RELEASE_COMMITS = "release-commits"
    TAG_RELEASE_COMMITS = "release-tag-commits"
    BRANCH_RELEASE_COMMITS = "release-branch-commits"
    RELEASE_LINES = "release-lines"
    TAG_RELEASE_LINES = "release-tag-lines"
    BRANCH_RELEASE_LINES = "release-branch-lines"
    RELEASE_AVG_PRS = "release-avg-prs"
    TAG_RELEASE_AVG_PRS = "release-tag-avg-prs"
    BRANCH_RELEASE_AVG_PRS = "release-branch-avg-prs"
    RELEASE_AVG_COMMITS = "release-avg-commits"
    TAG_RELEASE_AVG_COMMITS = "release-tag-avg-commits"
    BRANCH_RELEASE_AVG_COMMITS = "release-branch-avg-commits"
    RELEASE_AVG_LINES = "release-avg-lines"
    TAG_RELEASE_AVG_LINES = "release-tag-avg-lines"
    BRANCH_RELEASE_AVG_LINES = "release-branch-avg-lines"
    RELEASE_AGE = "release-age"
    TAG_RELEASE_AGE = "release-tag-age"
    BRANCH_RELEASE_AGE = "release-branch-age"
