from athenian.api.models.web.base_model_ import Model


class RepositorySetCreateRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    account: int
    items: list[str]
    name: str
