from typing import List

from athenian.api.models.web.base_model_ import Model


class RepositorySetWithName(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name: str = None, items: List[str] = None):
        """RepositorySetWithName - a model defined in OpenAPI

        :param name: The name of this RepositorySetWithName.
        :param items: The items of this RepositorySetWithName.
        """
        self.openapi_types = {"name": str, "items": List[str]}

        self.attribute_map = {"name": "name", "items": "items"}

        self._name = name
        self._items = items

    @property
    def name(self) -> str:
        """Gets the name of this RepositorySetWithName.

        :return: The name of this RepositorySetWithName.
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this RepositorySetWithName.

        :param name: The name of this RepositorySetWithName.
        """
        self._name = name

    @property
    def items(self) -> List[str]:
        """Gets the items of this RepositorySetWithName.

        :return: The items of this RepositorySetWithName.
        """
        return self._items

    @items.setter
    def items(self, items: List[str]):
        """Sets the items of this RepositorySetWithName.

        :param items: The items of this RepositorySetWithName.
        """
        self._items = items
