# coding: utf-8

from athenian.api import serialization
from athenian.api.models.web.base_model_ import Model


class RepositorySetList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):
        """RepositorySetList - a model defined in OpenAPI"""
        self.openapi_types = {}

        self.attribute_map = {}

    @classmethod
    def from_dict(cls, dikt: dict) -> "RepositorySetList":
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The RepositorySetList of this RepositorySetList.
        """
        return serialization.deserialize_model(dikt, cls)
