# coding: utf-8

from datetime import datetime
from typing import Optional

from athenian.api import serialization
from athenian.api.models.web.base_model_ import Model


class RepositorySetListItem(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(
        self,
        id: Optional[int] = None,
        created: Optional[datetime] = None,
        updated: Optional[datetime] = None,
        items_count: Optional[int] = None,
    ):
        """RepositorySetListItem - a model defined in OpenAPI

        :param id: The id of this RepositorySetListItem.
        :param created: The created of this RepositorySetListItem.
        :param updated: The updated of this RepositorySetListItem.
        :param items_count: The items_count of this RepositorySetListItem.
        """
        self.openapi_types = {
            "id": int,
            "created": datetime,
            "updated": datetime,
            "items_count": int,
        }

        self.attribute_map = {
            "id": "id",
            "created": "created",
            "updated": "updated",
            "items_count": "items_count",
        }

        self._id = id
        self._created = created
        self._updated = updated
        self._items_count = items_count

    @classmethod
    def from_dict(cls, dikt: dict) -> "RepositorySetListItem":
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The RepositorySetListItem of this RepositorySetListItem.
        """
        return serialization.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the epository set identifier of this RepositorySetListItem.

        :return: The id of this RepositorySetListItem.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the repository set identifier of this RepositorySetListItem.

        :param id: The id of this RepositorySetListItem.
        :type id: int
        """
        self._id = id

    @property
    def created(self) -> datetime:
        """Gets the created of this RepositorySetListItem.

        Date and time of creation of the repository set.

        :return: The created of this RepositorySetListItem.
        :rtype: date
        """
        return self._created

    @created.setter
    def created(self, created: datetime):
        """Sets the created of this RepositorySetListItem.

        Date and time of creation of the repository set.

        :param created: The created of this RepositorySetListItem.
        :type created: date
        """
        self._created = created

    @property
    def updated(self) -> datetime:
        """Gets the updated of this RepositorySetListItem.

        Date and time of the last change of the repository set.

        :return: The updated of this RepositorySetListItem.
        :rtype: date
        """
        return self._updated

    @updated.setter
    def updated(self, updated: datetime):
        """Sets the updated of this RepositorySetListItem.

        Date and time of the last change of the repository set.

        :param updated: The updated of this RepositorySetListItem.
        :type updated: date
        """
        self._updated = updated

    @property
    def items_count(self) -> int:
        """Gets the items_count of this RepositorySetListItem.

        Number of repositories in the set.

        :return: The items_count of this RepositorySetListItem.
        :rtype: int
        """
        return self._items_count

    @items_count.setter
    def items_count(self, items_count: int):
        """Sets the items_count of this RepositorySetListItem.

        Number of repositories in the set.

        :param items_count: The items_count of this RepositorySetListItem.
        :type items_count: int
        """
        self._items_count = items_count
