from datetime import datetime

from athenian.api.models.web.base_model_ import Model


class RepositorySetListItem(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    id: int
    name: str
    created: datetime
    updated: datetime
    items_count: int
