name: Cancel
on:
  push:
    branches:
    - '!master'
  pull_request_target:

jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          workflow_id: 3541504, 10042597
          access_token: ${{ github.token }}